### ISSUE TITLE
Tensor error

### ISSUE THREAD

**Issue by Crista23** [kumikokashii/lstm-text-generator#2]
Traceback (most recent call last):
  File "LSTM_generate_text.py", line 123, in <module>
    outputs_all_i = tf.concat(0, [outputs_all_i, output])
  File "/home/usr/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/usr/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/home/usr/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/usr/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/usr/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/usr/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/usr/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by julienknaf** [comment]
Arguments' order has changed in tf.concat:

https://www.tensorflow.org/api_docs/python/tf/concat

concat(
    values,
    axis,
    name='concat'
)

tf.concat(0, [outputs_all_i, output]) becomes tf.concat([outputs_all_i, output], 0)

**Comment by kumikokashii** [comment]
Thank you @Crista23 for running the code! I've uploaded the 2nd version of this project if interested :)

Thank you @julienknaf for the solution!
